name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Nexus
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_PASS }}
          repository: registry.haveacry.com/speedster/bedrock-test
          tag_with_ref: true
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_PASS }}
          repository: registry.haveacry.com/speedster/bedrock-test
          tags: latest
